Project2_QLSVLDA/Areas/Teacher/Controllers/GVClassController.cs
using Project2_QLSVLDA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Project2_QLSVLDA.Content.Custom.Class;
namespace Project2_QLSVLDA.Areas.Teacher.Controllers
{


    public class GVClassController : Controller
    {
        // GET: Teacher/GVClass
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("DangNhap", "HomeAdmin", new { area = "Admin" });
            }
            else
            {
                QL_PROJECTEntities db = new QL_PROJECTEntities();
                var session = Session["user"].ToString();
                List<LOPMONHOC> lop = db.LOPMONHOCs.Where(m => m.magv == session).ToList();



                return View(lop);
            }
        }

        [HttpGet]
        [Route("Detail/{id}")]
        public ActionResult Detail(string id)
        {

            ClassID model = new ClassID();
            model.Id = id;
            // Gán giá trị cho các thuộc tính khác của model


            if (Session["user"] == null)
            {
                return RedirectToAction("DangNhap", "HomeAdmin", new { area = "Admin" });
            }
            else
            {

                return View(model);
            }
        }

    }
}

Project2_QLSVLDA/Areas/Teacher/Views/GVClass/Detail.cshtml
@model Project2_QLSVLDA.Content.Custom.Class.ClassID

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Teacher/Views/Shared/_layout.cshtml";
}

@{
    var id_to_cp = Model.Id;
}

@{
    var db = new Project2_QLSVLDA.Models.QL_PROJECTEntities();
    var ketqua_orgin = (from svmh in db.SINHVIENMONHOCs
                        join sv in db.SINHVIENs on svmh.mssv equals sv.massv
                        join nsv in db.NHOMSINHVIENs on svmh.mssv equals nsv.masinhvien
                        where svmh.malop == id_to_cp && nsv.malop == id_to_cp
                        select new
                        {
                            svmh.mssv,
                            svmh.malop,
                            nsv.nhom,
                            sv.ten
                        }).ToList();

    var nhomKhacNhau = ketqua_orgin.Select(item => item.nhom).Distinct().ToArray();

    var ketqua_hienthi = ketqua_orgin;
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">

                    <li class="breadcrumb-item"><a href="@Url.Action("Index","GiaoVienHome")">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index","GVClass")">Danh sách lớp</a></li>

                    @*<li class="breadcrumb-item active">Danh sách lớp</li>*@
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="container-fluid">
    <div class="row">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="myDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Chọn nhóm
            </button>
            <div class="dropdown-menu" aria-labelledby="myDropdown">
                @foreach (var item in nhomKhacNhau)
                {
                    <a class="dropdown-item" onclick="filterTable('@item.ToString().Trim()')">@item</a>
                }
            </div>
        </div>

        <button type="button" class="btn btn-outline-danger" onclick="resetTable()" style="margin-left: 16px;">
            <i class="fas fa-times"></i>
        </button>
    </div>

    <div class="row">
        <table class="table table-bordered">
            <tr>
                <th>
                    MSSV
                </th>
                <th>
                    Tên
                </th>
                <th>
                    Nhóm
                </th>
                <th>
                    Chi tiết
                </th>
            </tr>
            @foreach (var item in ketqua_hienthi)
            {
                <tr class="data-row">
                    <td>
                        @item.mssv
                    </td>
                    <td>
                        @item.ten
                    </td>
                    <td>
                        @item.nhom
                    </td>
                    <td>
                        <a href="/Teacher/DetailStudent/Details/@item.mssv.Trim()">Details</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<script>
    // Function to filter the table based on selected nhom
    function filterTable(nhom) {
        var rows = document.getElementsByClassName("data-row");
        for (var i = 0; i < rows.length; i++) {
            var row = rows[i];
            var nhomCell = row.getElementsByTagName("td")[2]; // Index of 'Nhóm' column

            if (nhomCell.textContent.trim() === nhom) {
                row.style.display = "";
            } else {
                row.style.display = "none";
            }
        }
    }

    // Function to reset the table to show all rows
    function resetTable() {
        var rows = document.getElementsByClassName("data-row");
        for (var i = 0; i < rows.length; i++) {
            rows[i].style.display = "";
        }
    }
</script>

Project2_QLSVLDA/Areas/Teacher/Views/GVClass/Index.cshtml
@model List<Project2_QLSVLDA.Models.LOPMONHOC>


@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Teacher/Views/Shared/_layout.cshtml";

}




<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">

                    <li class="breadcrumb-item"><a href="@Url.Action("Index","GiaoVienHome")">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Danh sách lớp</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            @foreach (var item in Model)
            {

                <div class="col-sm-2">
                    <a href="@Url.Action("Detail", new {id = item.malop.Trim()})" class="card text-center">


                        @{ 
                            var str = item.mamonhoc.Trim();
                        }

                        @if (str == "IT3910Q")
                        {
                            <img src="~/Content/Custom/Img/img-pro-1.png" alt="Ảnh">
                        }
                        else if (str == "IT3920Q")
                        {
                            <img src="~/Content/Custom/Img/img-pro-2.png" alt="Ảnh">
                        }
                        else if (str == "IT3930Q")
                        {
                            <img src="~/Content/Custom/Img/img-pro-3.png" alt="Ảnh">
                        }
                        else if (str == "IT5315Q")
                        {
                            <img src="~/Content/Custom/Img/img-DATN.png" alt="Ảnh">
                        }



                        <div class="card-body">
                            <p class="card-text">Mã lớp: <span>@item.malop</span></p>
                        </div>

                    </a>
                </div>

            }

        </div>
    </div>
</section>