Project2_QLSVLDA/Areas/Student/Controllers/SinhVienHomeController.cs
using Project2_QLSVLDA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project2_QLSVLDA.Areas.Student.Controllers
{
    public class SinhVienHomeController : Controller
    {
        // GET: Student/SinhVienHome
        QL_PROJECTEntities db = new QL_PROJECTEntities();
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("DangNhap", "HomeAdmin", new { area = "Admin" });
            }
            else
            {

                return View();
            }

        }

        public JsonResult GetEvents()
        {

            string str = Session["user"].ToString();
            var list_cuoc_hen_sinh_vien = (from ch in db.CUOCHENs
                                          join svch in db.SINHVIENCUOCHENs on ch.macuochen equals svch.macuochen
                                          where svch.masinhvien.Trim() == str
                                          select ch).ToList();



            return Json(list_cuoc_hen_sinh_vien.AsEnumerable().Select(e => new
            {
                title = e.diadiem,
                start = e.thoigianbatdau.Value.ToString("yyyy/MM/dd HH:mm"),
                end = e.thoigianketthuc.Value.ToString("yyyy/MM/dd HH:mm")

            }).ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

Project2_QLSVLDA/Areas/Student/Views/SinhVienHome/Index.cshtml
@{
    Layout = "~/Areas/Student/Views/Shared/_Layout.cshtml";
}

@{
    var db = new Project2_QLSVLDA.Models.QL_PROJECTEntities();
    var user_ses = Session["user"].ToString();

    var list_sinhvienmonhoc = db.SINHVIENMONHOCs.Where(m => m.mssv == user_ses).ToList();
    var solophoc = list_sinhvienmonhoc.Select(m => m.mssv).Distinct().Count();


    var list_bt_lop = (from bt in db.BAITAPs
                       join nsv in db.NHOMSINHVIENs on bt.malop equals nsv.malop
                       where nsv.masinhvien.Trim() == user_ses && bt.manhom == nsv.nhom
                       select bt).ToList();
    var sobaitap = list_bt_lop.Count();


    var cuochen_allsystem = (from ch in db.CUOCHENs
                             join gv in db.GIANGVIENs on ch.magiaovien equals gv.magv
                             join svch in db.SINHVIENCUOCHENs on ch.macuochen equals svch.macuochen
                             select new
                             {
                                 ch.macuochen,
                                 ch.magiaovien,
                                 ch.thoigianbatdau,
                                 ch.thoigianketthuc,
                                 gv.ten,
                                 ch.tinhtrang,
                                 ch.diadiem,
                                 svch.thoigiandat,
                                 ch.ghichu,
                                 svch.masinhvien

                             }).ToList();


    var ds_lop_sv_hoc = (from lmh in db.LOPMONHOCs
                         join svmh in db.SINHVIENMONHOCs on lmh.malop equals svmh.malop
                         where svmh.mssv == user_ses
                         select lmh.magv).ToList();

    //var nhomKhacNhau = list_cuoc_hen.Select(item => item.malop).Distinct().ToArray();


    var list_cuoc_hen = cuochen_allsystem.Where(p => ds_lop_sv_hoc.Contains(p.magiaovien) && p.masinhvien.Trim() == user_ses).ToList();
    var so_cuoc_hen = list_cuoc_hen.Count();


}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">Trang chủ</li>
                    @*<li class="breadcrumb-item"><a href="@Url.Action("Index","GiaoVienHome")">Trang chủ</a></li>*@
                    @*<li class="breadcrumb-item active">Contact us</li>*@
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Modal để hiển thị chi tiết nội dung sự kiện -->
<div id="eventModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <div id="eventDetails"></div>
    </div>
</div>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>@solophoc</h3>

                        <p>Số lớp hiện có</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="@Url.Action("Index","SVClass")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>@sobaitap</h3>

                        <p>Số bài tập hiện có</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="@Url.Action("Index","SubmitAssignment")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@so_cuoc_hen</h3>

                        <p>Số cuộc hẹn hiện có</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="@Url.Action("HistoryBook","SV_Meeting")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-7 connectedSortable">

                <!-- Calendar List -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="ion ion-clipboard mr-1"></i>
                            Calendar
                        </h3>


                    </div>
                    <!-- /.card-header -->
                    <div class="body-content">
                        <div id='calendar'></div>
                    </div>
                </div>
                <!-- /.card -->
            </section>
            <!-- /.Left col -->
            <!-- right col (We are only adding the ID to make the widgets sortable)-->
            <section class="col-lg-5 connectedSortable">


                <!-- Calendar -->
                <div class="containers">
                    <div class="display-date">
                        <span id="day">day</span>,
                        <span id="daynum">00</span>
                        <span id="month">month</span>
                        <span id="year">0000</span>
                    </div>
                    <div class="display-time"></div>
                </div>

                <!-- /.card -->
            </section>
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->




@section CSS {

    <link href="~/Content/Custom/clocktime.css" rel="stylesheet" />

    <!-- CSS Includes -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.css" />

    <style type="text/css">

        .field-validation-error {
            color: #ff0000;
        }
    </style>

}

@section JS {

    <script src="~/Content/Custom/clocktime.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/mvc/4.0/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.js"></script>

    <script type="text/javascript">

       // Hàm lấy dữ liệu sự kiện từ máy chủ
        function getEventsFromServer() {
            return $.ajax({
                url: '@Url.Action("GetEvents", "SinhVienHome")',
                type: 'GET',
                dataType: 'json'
            });
        }


        // Khởi tạo lịch
        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month'
            },
            firstDay: 1, // The day that each week begins (Monday=1)
            slotMinutes: 60,
            events: function (start, end, timezone, callback) {
                // Gọi hàm lấy dữ liệu sự kiện từ máy chủ
                getEventsFromServer().done(function (eventsData) {
                    callback(eventsData);
                });
            }

        });

    </script>


}